### ISSUE TITLE
Control panel - change bg-color of the menu

### ISSUE THREAD

**Issue by pklimczu** [pklimczu/GeoGuesserScoreboard#3]
It should be possible to change the bg-color of the menu (some people may do not like that shade of red).

**Comment by acomplak** [comment]
Change is waiting for approval (branch: adcojs).

**Comment by pklimczu** [comment]
Thanks acomplak!
I would like to improve here two things:

- the color of the menu "blinks" when the pages is loading - could you try to solve the issue?

- it would be great to have a button for reseting the color

**Comment by pklimczu** [comment]
![2019-08-06_19-57-27](https://user-images.githubusercontent.com/5957413/62564163-a41bf400-b884-11e9-8580-0ada944a9fc4.gif)
I have attached a short gif to give you better understanding what's going on.

**Comment by pklimczu** [comment]
Implemented
